---
title: "media_enquiries"
author: "Ivone Wardell"
date: '2018-10-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libraries used
library(reshape2, dplyr, ggplot2, tidyr, tidytext, wordcloud)
```

```{r}
media <- NEB_Media_Inquiries_2006_2018_2
media$Organization

#summarize by organization
med_org <- media %>% group_by(Organization) %>% 
        summarise(n = n())

#which organizations have more than 50 media enquires
med_top_org <- med_org %>% filter(n > 50)
top_org <- as.character(med_top_org$Organization)

#filter the top organizations
top_media <- media %>% filter(Organization %in% top_org)


#fix orgs names
a <- which(top_media$Organization == "bloomberg news")
top_media$Organization[a] <- "bloomberg"

b <- which(top_media$Organization == "cbc north")
top_media$Organization[b] <- "cbc"

c <- which(top_media$Organization == "radio-canada")
top_media$Organization[c] <- "radio canada"



```

```{r}
data("stop_words")

test <- readLines("~/PycharmProjects/untapped/contributed-data/4_social_license/NEB applications/Enbridge_Northern_Gateway.txt")

# test <- readLines("~/PycharmProjects/untapped/contributed-data/4_social_license/Factiva/Factiva_News_Articles.txt")

#work with questions column
#test <- top_media$Question[c(1:2729)]

#generate data frame 
test_df <- data_frame(test)
test_df <- test_df %>% unnest_tokens(word, test) %>% 
        anti_join(stop_words)

#plot all words
test_df %>% 
        count(word, sort = TRUE) %>% 
        filter(n > 30) %>% 
        mutate(word = reorder(word, n)) %>% 
        ggplot(aes(x = word, y = n)) + 
        geom_col() + 
        xlab(NULL) + 
        coord_flip()

#get sentiment 
bing_words <- test_df %>% 
        inner_join(get_sentiments("bing")) %>% 
        count(word, sentiment, sort = TRUE)

#plot
bing_words %>% 
        group_by(sentiment) %>% 
        top_n(20) %>% 
        ungroup() %>% 
        mutate(word = reorder(word, n)) %>% 
        ggplot(aes(word, n, fill = sentiment)) + 
        geom_col(show.legend = FALSE) + 
        facet_wrap(~sentiment, scales = "free_y") + 
        labs(y = "Contribution to sentiment", 
             x = NULL) + 
        coord_flip()
```

```{r}
#word cloud
test_df %>% 
        anti_join(stop_words) %>% 
        count(word) %>% 
        with(wordcloud(word, n, max.words = 100))
```

```{r}
#negate & positive word cloud
test_df %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("red", "blue"),
                   max.words = 50)
```
